pool:
  name: Default
  demands:
    - agent.name -equals AGENTDOCKERTEST

variables:
  web_app_name: 'app-CinemasBackEnd-240118221846'
  azureServiceConnectionId: 'srv_con_backend'
  javaVersion: '17'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        steps:
          - checkout: self
          - script: |
              mvn clean package
            displayName: 'Build Maven project'

          - task: AzureWebApp@1
            displayName: '
            
            : $(web_app_name)'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(web_app_name)
              package: $(Build.SourcesDirectory)/target/CinemaPFE-0.0.1-SNAPSHOT.jar
              deploymentMethod: zipDeploy
              runtimeStack: 'JAVA|17'